CREATE TABLE IF NOT EXISTS products_tags(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT fk_tag FOREIGN KEY (tag_id) REFERENCES tags_for_products(id) ON DELETE RESTRICT,
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
    CONSTRAINT uq_product_tag UNIQUE (product_id, tag_id)
);

CREATE INDEX idx_products_tag_search ON products_tags (tag_id);