CREATE TABLE IF NOT EXISTS modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE, -- Identificador único para i18n
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Pre-poblamos con las claves de traducción en lugar de los textos
INSERT INTO modules (code) VALUES
('MODULE_PRODUCTS'),
('MODULE_STORES'),
('MODULE_SALES'),
('MODULE_EMPLOYEES')
ON CONFLICT (code) DO NOTHING;
