CREATE TABLE IF NOT EXISTS employee_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID NOT NULL,
    store_id BIGINT NOT NULL,
    module_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL, -- Ej: 'CREATE', 'READ', 'UPDATE', 'DELETE'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_emp_perm_employee FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE,
    CONSTRAINT fk_emp_perm_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
    CONSTRAINT fk_emp_perm_module FOREIGN KEY (module_id) REFERENCES modules (id) ON DELETE CASCADE,
    
    -- Esta restricción asegura que no se duplique exactamente el mismo permiso en la misma tienda
    CONSTRAINT uq_employee_store_module_action UNIQUE (employee_id, store_id, module_id, action)
);

-- Opcional pero recomendado: Índices para búsquedas rápidas al interceptar peticiones en el backend
CREATE INDEX idx_employee_permissions_lookup ON employee_permissions(employee_id, store_id, module_id);
