CREATE SCHEMA IF NOT EXISTS identity;

CREATE TABLE IF NOT EXISTS identity.owners (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company            TEXT,
    name              VARCHAR(100) NOT NULL,
    last_name         VARCHAR(100) NOT NULL,
    email             VARCHAR(255) UNIQUE NOT NULL,
    password          VARCHAR(255) NOT NULL,
    organization_code VARCHAR(10) UNIQUE,
    is_active         BOOLEAN DEFAULT TRUE,
    last_login        TIMESTAMP WITH TIME ZONE,
    schema_name       VARCHAR(63) UNIQUE,
    created_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION identity.create_owners(schema_name TEXT) 
RETURNS VOID AS $$ 
BEGIN 
    -- 1. Crear el esquema
    EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', schema_name);
    
    -- 2. Cambiar el path
    EXECUTE format('SET LOCAL search_path TO %I', schema_name);

    -- Crear tabla regions
    CREATE TABLE IF NOT EXISTS regions (
        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name       VARCHAR(255) NOT NULL,
        timezone   VARCHAR(50) DEFAULT 'America/Mexico_City',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    -- Crear tabla stores
    CREATE TABLE IF NOT EXISTS stores (
        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        region_id  BIGINT,
        name       VARCHAR(255) NOT NULL,
        address    TEXT,
        status     VARCHAR(50) DEFAULT 'active',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_stores_region FOREIGN KEY (region_id) REFERENCES regions(id) ON DELETE RESTRICT
    );

    -- Crear índice
    CREATE INDEX IF NOT EXISTS idx_stores_region_id 
    ON stores(region_id)
    WHERE region_id IS NOT NULL;


    -- Crear tabla users
    CREATE TABLE IF NOT EXISTS users (
        id             SERIAL PRIMARY KEY, 
        username       VARCHAR(100) NOT NULL, 
        password       VARCHAR(100) NOT NULL,
        created_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        last_active_at TIMESTAMP WITH TIME ZONE,
        deleted_at     TIMESTAMP WITH TIME ZONE
    );
    
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION identity.update_updated_at_column() 
RETURNS TRIGGER AS $$ 
BEGIN 
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_owners_updated_at ON identity.owners;

CREATE TRIGGER tr_owners_updated_at 
BEFORE UPDATE ON identity.owners 
FOR EACH ROW 
EXECUTE FUNCTION identity.update_updated_at_column();