-- Crear tabla stores
CREATE TABLE IF NOT EXISTS stores (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id  BIGINT,
    name       VARCHAR(255) NOT NULL,
    address    TEXT,
    status     VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stores_region FOREIGN KEY (region_id) REFERENCES regions(id) ON DELETE RESTRICT
);

-- Crear índice
CREATE INDEX IF NOT EXISTS idx_stores_region_id 
ON stores(region_id)
WHERE region_id IS NOT NULL;